include ${IAC_DIR}/modules.mk

MODULES = ../base/networking/vpc								\
		  ../base/networking/security-groups/ssh-access			\
		  ../base/networking/security-groups/msk-access			\
		  ../base/msk/cluster-config							\
		  ../base/msk/cluster									\
		  ../base/iam/permission-policies/topic-owner			\
		  ../base/iam/permission-policies/topic-read			\
		  ../base/iam/permission-policies/topic-write			\
		  ./iam/roles/topic-owner								\
		  ./iam/roles/topic-read								\
		  ./iam/roles/topic-write								\
		  ./ec2/topic-owner										\
		  ./ec2/topic-read										\
		  ./ec2/topic-write
