include ${IAC_DIR}/modules.mk

MODULES = ../base/networking/vpc								\
		  ../base/networking/security-groups/ssh-access			\
		  ../base/networking/security-groups/msk-access			\
		  ../base/msk/cluster-config							\
		  ../base/msk/cluster									\
		  ../base/iam/permission-policies/cluster-admin			\
		  ../base/iam/permission-policies/topic-owner			\
		  ../base/iam/permission-policies/topic-read			\
		  ../base/iam/permission-policies/topic-write			\
		  ../base/eks/iam/roles/eks-cluster						\
		  ../base/eks/iam/roles/eks-nodes						\
		  ../base/eks/cluster									\
		  ../base/eks/nodes										\
		  ../base/eks/iam/eks-oidc-provider						\
		  ./iam/roles/topic-owner								\
		  ./iam/roles/topic-read								\
		  ./iam/roles/topic-write
